name: Testing on .NET Core

on:
  push:
    branches: [ master, hunamizawa/develop ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        dotnet: [ '2.1', '3.1' ]
    
    env:
      FRAMEWORK: ${{ format('netcoreapp{0}', matrix.dotnet) }}

    name: .NET Core ${{ matrix.dotnet }}   
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ format('{0}.x', matrix.dotnet) }}
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore --framework $FRAMEWORK
    - name: Test
      run: dotnet test --no-restore --verbosity normal --framework $FRAMEWORK
