name: Testing on .NET Core

on:
  push:
    branches: [ master, hunamizawa/develop ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        dotnet: [ '2.1', '3.1' ]
    
    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
      FRAMEWORK: ${{ format('netcoreapp{0}', matrix.dotnet) }}

    name: .NET Core ${{ matrix.dotnet }}   
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ format('{0}.x', matrix.dotnet) }}
    - name: Build
      run: dotnet build --configuration Release --framework ${{ env.FRAMEWORK }}
    - name: Test
      run: dotnet test --no-build --framework ${{ env.FRAMEWORK }}
